// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_center.proto

package userrepositoryrpc

import (
	"context"

	"github.com/Auroraol/cloud-storage/tree/main/cloud-storage-back-end/user_center/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVolumeReq            = pb.AddVolumeReq
	AddVolumeResp           = pb.AddVolumeResp
	CreateByShareReply      = pb.CreateByShareReply
	CreateByShareReq        = pb.CreateByShareReq
	DecreaseVolumeReq       = pb.DecreaseVolumeReq
	DecreaseVolumeResp      = pb.DecreaseVolumeResp
	FindRepositoryIdReply   = pb.FindRepositoryIdReply
	FindRepositoryIdReq     = pb.FindRepositoryIdReq
	FindVolumeReq           = pb.FindVolumeReq
	FindVolumeResp          = pb.FindVolumeResp
	RepositoryIdReq         = pb.RepositoryIdReq
	UserRepositoryNameReply = pb.UserRepositoryNameReply

	UserRepositoryRpc interface {
		GetUserRepositoryNameByRepositoryId(ctx context.Context, in *RepositoryIdReq, opts ...grpc.CallOption) (*UserRepositoryNameReply, error)
		FindRepositoryIdById(ctx context.Context, in *FindRepositoryIdReq, opts ...grpc.CallOption) (*FindRepositoryIdReply, error)
		CreateByShare(ctx context.Context, in *CreateByShareReq, opts ...grpc.CallOption) (*CreateByShareReply, error)
	}

	defaultUserRepositoryRpc struct {
		cli zrpc.Client
	}
)

func NewUserRepositoryRpc(cli zrpc.Client) UserRepositoryRpc {
	return &defaultUserRepositoryRpc{
		cli: cli,
	}
}

func (m *defaultUserRepositoryRpc) GetUserRepositoryNameByRepositoryId(ctx context.Context, in *RepositoryIdReq, opts ...grpc.CallOption) (*UserRepositoryNameReply, error) {
	client := pb.NewUserRepositoryRpcClient(m.cli.Conn())
	return client.GetUserRepositoryNameByRepositoryId(ctx, in, opts...)
}

func (m *defaultUserRepositoryRpc) FindRepositoryIdById(ctx context.Context, in *FindRepositoryIdReq, opts ...grpc.CallOption) (*FindRepositoryIdReply, error) {
	client := pb.NewUserRepositoryRpcClient(m.cli.Conn())
	return client.FindRepositoryIdById(ctx, in, opts...)
}

func (m *defaultUserRepositoryRpc) CreateByShare(ctx context.Context, in *CreateByShareReq, opts ...grpc.CallOption) (*CreateByShareReply, error) {
	client := pb.NewUserRepositoryRpcClient(m.cli.Conn())
	return client.CreateByShare(ctx, in, opts...)
}
