// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AccountLoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type AccountLoginResp struct {
	AccessToken  string `json:"accesssToken"` // access_token
	AccessExpire int64  `json:"accessExpire"` // access_token的过期时间
	RefreshAfter int64  `json:"refreshAfter"` // 刷新token之前剩余的时间
}

type AccountRegisterReq struct {
	Name     string `json:"name"`     // 用户名称
	Password string `json:"password"` // 用户密码
}

type AccountRegisterResp struct {
}

type CodeSendRequest struct {
	Email string `json:"email"`
}

type CodeSendResponse struct {
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RefreshAuthRequest struct {
}

type RefreshAuthResponse struct {
	AccessToken  string `json:"accesssToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Name     string `json:"name,optional"`     // 用户名称
	Mobile   string `json:"mobile,optional"`   // 手机号
	Password string `json:"password,optional"` // 用户密码
	Code     string `json:"code,optional"`     // 验证码
}

type RegisterResp struct {
}

type User struct {
	Id       int64  `json:"id"`
	Username string `db:"username"` // 用户名
	Mobile   string `db:"mobile"`   // 手机号
	Nickname string `db:"nickname"` // 昵称
	Gender   int64  `db:"gender"`   // 性别，1：男，0：女，默认为1
	Avatar   string `db:"avatar"`   // 用户头像
	Birthday string `db:"birthday"` // 生日
	Email    string `db:"email"`    // 电子邮箱
	Brief    string `db:"brief"`    // 简介|个性签名
	Info     string `db:"info"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
