// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/logic"
	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/svc"
	"github.com/Auroraol/cloud-storage/user_center/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) DecreaseVolume(ctx context.Context, in *pb.DecreaseVolumeReq) (*pb.DecreaseVolumeResp, error) {
	l := logic.NewDecreaseVolumeLogic(ctx, s.svcCtx)
	return l.DecreaseVolume(in)
}

func (s *UserCenterServer) FindVolumeById(ctx context.Context, in *pb.FindVolumeReq) (*pb.FindVolumeResp, error) {
	l := logic.NewFindVolumeByIdLogic(ctx, s.svcCtx)
	return l.FindVolumeById(in)
}

func (s *UserCenterServer) AddVolume(ctx context.Context, in *pb.AddVolumeReq) (*pb.AddVolumeResp, error) {
	l := logic.NewAddVolumeLogic(ctx, s.svcCtx)
	return l.AddVolume(in)
}
