// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: log_service.proto

package auditservicerpc

import (
	"context"

	"github.com/Auroraol/cloud-storage/log_service/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteSshInfoReq  = pb.DeleteSshInfoReq
	GetSshInfosReq    = pb.GetSshInfosReq
	OperationLogReq   = pb.OperationLogReq
	OperationLogResp  = pb.OperationLogResp
	SshInfoDetailResp = pb.SshInfoDetailResp
	SshInfoListResp   = pb.SshInfoListResp
	SshInfoReq        = pb.SshInfoReq
	SshInfoResp       = pb.SshInfoResp

	AuditServiceRpc interface {
		// 创建操作记录
		CreateOperationLog(ctx context.Context, in *OperationLogReq, opts ...grpc.CallOption) (*OperationLogResp, error)
	}

	defaultAuditServiceRpc struct {
		cli zrpc.Client
	}
)

func NewAuditServiceRpc(cli zrpc.Client) AuditServiceRpc {
	return &defaultAuditServiceRpc{
		cli: cli,
	}
}

// 创建操作记录
func (m *defaultAuditServiceRpc) CreateOperationLog(ctx context.Context, in *OperationLogReq, opts ...grpc.CallOption) (*OperationLogResp, error) {
	client := pb.NewAuditServiceRpcClient(m.cli.Conn())
	return client.CreateOperationLog(ctx, in, opts...)
}
