// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.0--rc2
// source: user_center.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecreaseVolumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseVolumeReq) Reset() {
	*x = DecreaseVolumeReq{}
	mi := &file_user_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseVolumeReq) ProtoMessage() {}

func (x *DecreaseVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseVolumeReq.ProtoReflect.Descriptor instead.
func (*DecreaseVolumeReq) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{0}
}

func (x *DecreaseVolumeReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecreaseVolumeReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DecreaseVolumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseVolumeResp) Reset() {
	*x = DecreaseVolumeResp{}
	mi := &file_user_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseVolumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseVolumeResp) ProtoMessage() {}

func (x *DecreaseVolumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseVolumeResp.ProtoReflect.Descriptor instead.
func (*DecreaseVolumeResp) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{1}
}

type FindVolumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVolumeReq) Reset() {
	*x = FindVolumeReq{}
	mi := &file_user_center_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVolumeReq) ProtoMessage() {}

func (x *FindVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVolumeReq.ProtoReflect.Descriptor instead.
func (*FindVolumeReq) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{2}
}

func (x *FindVolumeReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindVolumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NowVolume     int64                  `protobuf:"varint,1,opt,name=nowVolume,proto3" json:"nowVolume,omitempty"`
	TotalVolume   int64                  `protobuf:"varint,2,opt,name=totalVolume,proto3" json:"totalVolume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVolumeResp) Reset() {
	*x = FindVolumeResp{}
	mi := &file_user_center_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVolumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVolumeResp) ProtoMessage() {}

func (x *FindVolumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVolumeResp.ProtoReflect.Descriptor instead.
func (*FindVolumeResp) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{3}
}

func (x *FindVolumeResp) GetNowVolume() int64 {
	if x != nil {
		return x.NowVolume
	}
	return 0
}

func (x *FindVolumeResp) GetTotalVolume() int64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

type AddVolumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVolumeReq) Reset() {
	*x = AddVolumeReq{}
	mi := &file_user_center_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVolumeReq) ProtoMessage() {}

func (x *AddVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVolumeReq.ProtoReflect.Descriptor instead.
func (*AddVolumeReq) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{4}
}

func (x *AddVolumeReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddVolumeReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AddVolumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVolumeResp) Reset() {
	*x = AddVolumeResp{}
	mi := &file_user_center_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVolumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVolumeResp) ProtoMessage() {}

func (x *AddVolumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_center_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVolumeResp.ProtoReflect.Descriptor instead.
func (*AddVolumeResp) Descriptor() ([]byte, []int) {
	return file_user_center_proto_rawDescGZIP(), []int{5}
}

var File_user_center_proto protoreflect.FileDescriptor

var file_user_center_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x37, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x72, 0x65,
	0x61, 0x73, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1f, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x77,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x6f,
	0x77, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0xb8,
	0x01, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a,
	0x0e, 0x64, 0x65, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x72,
	0x65, 0x61, 0x73, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37,
	0x0a, 0x0e, 0x66, 0x69, 0x6e, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_center_proto_rawDescOnce sync.Once
	file_user_center_proto_rawDescData = file_user_center_proto_rawDesc
)

func file_user_center_proto_rawDescGZIP() []byte {
	file_user_center_proto_rawDescOnce.Do(func() {
		file_user_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_center_proto_rawDescData)
	})
	return file_user_center_proto_rawDescData
}

var file_user_center_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_center_proto_goTypes = []any{
	(*DecreaseVolumeReq)(nil),  // 0: pb.DecreaseVolumeReq
	(*DecreaseVolumeResp)(nil), // 1: pb.DecreaseVolumeResp
	(*FindVolumeReq)(nil),      // 2: pb.FindVolumeReq
	(*FindVolumeResp)(nil),     // 3: pb.FindVolumeResp
	(*AddVolumeReq)(nil),       // 4: pb.AddVolumeReq
	(*AddVolumeResp)(nil),      // 5: pb.AddVolumeResp
}
var file_user_center_proto_depIdxs = []int32{
	0, // 0: pb.UserCenter.decreaseVolume:input_type -> pb.DecreaseVolumeReq
	2, // 1: pb.UserCenter.findVolumeById:input_type -> pb.FindVolumeReq
	4, // 2: pb.UserCenter.addVolume:input_type -> pb.AddVolumeReq
	1, // 3: pb.UserCenter.decreaseVolume:output_type -> pb.DecreaseVolumeResp
	3, // 4: pb.UserCenter.findVolumeById:output_type -> pb.FindVolumeResp
	5, // 5: pb.UserCenter.addVolume:output_type -> pb.AddVolumeResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_center_proto_init() }
func file_user_center_proto_init() {
	if File_user_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_center_proto_goTypes,
		DependencyIndexes: file_user_center_proto_depIdxs,
		MessageInfos:      file_user_center_proto_msgTypes,
	}.Build()
	File_user_center_proto = out.File
	file_user_center_proto_rawDesc = nil
	file_user_center_proto_goTypes = nil
	file_user_center_proto_depIdxs = nil
}
