# 日志配置
LogConfig:
  LogLevel: "debug"          # 日志级别: debug, info, warn, error
  LogFormat: "json"          # 日志格式: json
  LogPath: "./"              # 日志文件路径
  LogFileName: "file_processor.log" # 日志文件名
  LogFileMaxSize: 10         # 单个日志文件最大大小(MB)
  LogFileMaxBackups: 10      # 日志备份文件最多数量
  LogMaxAge: 60              # 日志保留天数
  LogCompress: false         # 是否压缩日志
  LogStdout: true            # 是否同时输出到控制台
  SeparateLevel: false       # 是否将不同级别的日志分开存储到不同文件

# 消费者Pulsar配置
SubConfig:
  Enabled: true
  URL: "pulsar://101.37.165.220:6650"
  Topic: "file-processed"
  SubscriptionName: "file-processor-sub"
  SubscriptionType: "Shared"
  SubscriptionInitialPosition: "Earliest"
  Name: "file-processor-consumer"
  AutoAck: false
