// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_center.proto

package userrepository

import (
	"context"

	"github.com/Auroraol/cloud-storage/user_center/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVolumeReq            = pb.AddVolumeReq
	AddVolumeResp           = pb.AddVolumeResp
	CreateByShareReply      = pb.CreateByShareReply
	CreateByShareReq        = pb.CreateByShareReq
	DecreaseVolumeReq       = pb.DecreaseVolumeReq
	DecreaseVolumeResp      = pb.DecreaseVolumeResp
	FindRepositoryIdReply   = pb.FindRepositoryIdReply
	FindRepositoryIdReq     = pb.FindRepositoryIdReq
	FindVolumeReq           = pb.FindVolumeReq
	FindVolumeResp          = pb.FindVolumeResp
	RepositoryIdReq         = pb.RepositoryIdReq
	UserRepositoryNameReply = pb.UserRepositoryNameReply

	UserRepository interface {
		GetUserRepositoryNameByRepositoryId(ctx context.Context, in *RepositoryIdReq, opts ...grpc.CallOption) (*UserRepositoryNameReply, error)
		FindRepositoryIdById(ctx context.Context, in *FindRepositoryIdReq, opts ...grpc.CallOption) (*FindRepositoryIdReply, error)
		CreateByShare(ctx context.Context, in *CreateByShareReq, opts ...grpc.CallOption) (*CreateByShareReply, error)
	}

	defaultUserRepository struct {
		cli zrpc.Client
	}
)

func NewUserRepository(cli zrpc.Client) UserRepository {
	return &defaultUserRepository{
		cli: cli,
	}
}

func (m *defaultUserRepository) GetUserRepositoryNameByRepositoryId(ctx context.Context, in *RepositoryIdReq, opts ...grpc.CallOption) (*UserRepositoryNameReply, error) {
	client := pb.NewUserRepositoryClient(m.cli.Conn())
	return client.GetUserRepositoryNameByRepositoryId(ctx, in, opts...)
}

func (m *defaultUserRepository) FindRepositoryIdById(ctx context.Context, in *FindRepositoryIdReq, opts ...grpc.CallOption) (*FindRepositoryIdReply, error) {
	client := pb.NewUserRepositoryClient(m.cli.Conn())
	return client.FindRepositoryIdById(ctx, in, opts...)
}

func (m *defaultUserRepository) CreateByShare(ctx context.Context, in *CreateByShareReq, opts ...grpc.CallOption) (*CreateByShareReply, error) {
	client := pb.NewUserRepositoryClient(m.cli.Conn())
	return client.CreateByShare(ctx, in, opts...)
}
