// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DeleteSSHConnectReq struct {
	SshId int64 `json:"ssh_id"`
}

type DeleteSSHConnectRes struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	SshId   int64  `json:"ssh_id"`
}

type FileStat struct {
	TotalFiles     int   `json:"total_files"`
	TotalDirs      int   `json:"total_dirs"`
	TotalSize      int64 `json:"total_size"`
	LogFileCount   int   `json:"log_file_count"`
	RecentModified int   `json:"recent_modified"`
}

type GetLocalFileContentReq struct {
	FilePath string `json:"file_path"`
	Offset   int64  `json:"offset,optional"`
	Limit    int64  `json:"limit,optional"`
}

type GetLocalFileContentRes struct {
	Content string `json:"content"`
	Length  int    `json:"length"`
}

type GetLocalLogFilesReq struct {
	Path string `json:"path"` // 目录路径
}

type GetLocalLogFilesRes struct {
	Files []LocalFileInfo `json:"files"`
	Stat  FileStat        `json:"stat"`
}

type GetLogFilesReq struct {
	Host string `json:"host"` // 主机地址
	Path string `json:"path"` // 日志路径
}

type GetLogFilesRes struct {
	Files   []string `json:"files"`   // 文件列表
	Success bool     `json:"success"` // 是否成功
}

type GetOperationLogReq struct {
	Page      int   `json:"page"`
	PageSize  int   `json:"page_size"`
	Flag      int   `json:"flag"`       //操作类型，0：上传，1：下载，2：删除，3.恢复 4：重命名，5：移动，6：复制，7：创建文件夹，8：修改文件, -1: 全部
	StartTime int64 `json:"start_time"` // 时间戳(秒)
	EndTime   int64 `json:"end_time"`   // 时间戳(秒)
}

type GetOperationLogRes struct {
	Total         int            `json:"total"`
	OperationLogs []OperationLog `json:"operation_logs"`
}

type GetSSHConnectReq struct {
}

type HistoryAnalysisReq struct {
	Host      string `json:"host, omitempty"`     // 主机地址
	LogFile   string `json:"log_file"`            // 日志文件名
	StartTime int64  `json:"start_time"`          // 开始时间
	EndTime   int64  `json:"end_time"`            // 结束时间
	Keywords  string `json:"keywords, omitempty"` // 关键字
}

type HistoryAnalysisRes struct {
	Data     []LogEntry `json:"data"`      // 日志条目
	Total    int        `json:"total"`     // 总数
	Page     int        `json:"page"`      // 页码
	PageSize int        `json:"page_size"` // 每页大小
	Success  bool       `json:"success"`   // 是否成功
}

type LocalFileInfo struct {
	Path      string `json:"path"`
	Name      string `json:"name"`
	Size      int64  `json:"size"`
	IsDir     bool   `json:"is_dir"`
	ModTime   string `json:"mod_time"`
	Extension string `json:"extension"`
}

type LocalLogEntry struct {
	Timestamp string `json:"timestamp"`
	Level     string `json:"level"`
	Content   string `json:"content"`
	Source    string `json:"source"`
	LineNum   int    `json:"line_num"`
}

type LocalMonitorData struct {
	Timestamp int64  `json:"timestamp"` // 时间戳
	Value     int    `json:"value"`     // 数量
	Type      string `json:"type"`      // 类型（请求数、错误数、响应时间）
	Caller    string `json:"caller"`
}

type LocalRealTimeMonitorReq struct {
	LogFile      string   `json:"log_file"`      // 日志文件名
	MonitorItems []string `json:"monitor_items"` // 监控项（requests,errors,debug_logs,info_logs,warn_logs,error_logs）
	TimeRange    int      `json:"time_range"`    // 时间范围（1小时、6小时、12小时、24小时）
}

type LocalRealTimeMonitorRes struct {
	Data    []LocalMonitorData `json:"data"`    // 监控数据
	Total   int                `json:"total"`   // 总数
	Success bool               `json:"success"` // 是否成功
}

type LogEntry struct {
	Timestamp int64  `json:"timestamp"` // 时间戳
	Content   string `json:"content"`   // 内容
	Level     string `json:"level"`     // 级别
	Value     int    `json:"value"`     // 数量
}

type MonitorData struct {
	Timestamp int64  `json:"timestamp"` // 时间戳
	Value     int    `json:"value"`     // 数量
	Type      string `json:"type"`      // 类型（请求数、错误数、响应时间）
	Caller    string `json:"caller"`
}

type OperationLog struct {
	Content   string `json:"content"`
	FileSize  int    `json:"file_size"`
	CreatedAt string `json:"created_at"`
	Flag      int    `json:"flag"`
	FileName  string `json:"file_name"`
	FileId    string `json:"file_id"`
}

type ReadLocalLogFileReq struct {
	FilePath   string `json:"path"`                 // 文件路径
	StartTime  string `json:"start_time,optional"`  // 开始时间，RFC3339格式
	EndTime    string `json:"end_time,optional"`    // 结束时间，RFC3339格式
	Level      string `json:"level,optional"`       // 日志级别
	Keyword    string `json:"keyword,optional"`     // 关键词
	MaxResults int    `json:"max_results,optional"` // 最大返回结果数
}

type ReadLocalLogFileRes struct {
	Entries []LocalLogEntry `json:"entries"`
	Total   int             `json:"total"`
}

type ReadLogFileReq struct {
	Host     string `json:"host"`      // 主机地址
	Path     string `json:"path"`      // 日志路径
	Match    string `json:"match"`     // 匹配字符串
	Page     int    `json:"page"`      // 页码
	PageSize int    `json:"page_size"` // 每页大小
}

type ReadLogFileRes struct {
	Contents   []string `json:"contents"`    // 内容
	TotalLines int      `json:"total_lines"` // 总行数
	Page       int      `json:"page"`        // 页码
	PageSize   int      `json:"page_size"`   // 每页大小
	Success    bool     `json:"success"`     // 是否成功
}

type RealTimeMonitorReq struct {
	Host         string   `json:"host"`          // 主机地址
	LogFile      string   `json:"log_file"`      // 日志文件名
	MonitorItems []string `json:"monitor_items"` // 监控项（requests,errors,debug_logs,info_logs,warn_logs,error_logs）
	TimeRange    int      `json:"time_range"`    // 时间范围（1小时、6小时、12小时、24小时）
}

type RealTimeMonitorRes struct {
	Data    []MonitorData `json:"data"`    // 监控数据
	Total   int           `json:"total"`   // 总数
	Success bool          `json:"success"` // 是否成功
}

type SSHConnectReq struct {
	Host           string `json:"host"` // 主机地址
	Port           int    `json:"port"`
	User           string `json:"user"`                       // 用户名
	Password       string `json:"password"`                   // 密码
	PrivateKeyPath string `json:"private_key_path, optional"` // 私钥路径
}

type SSHConnectRes struct {
	Success bool   `json:"success"` // 是否成功
	Message string `json:"message"` // 消息
}

type SshInfoDetailResp struct {
	UserId   int64  `json:"user_id"`  // 关联用户ID
	SshId    int64  `json:"ssh_id"`   // SSH记录ID
	Host     string `json:"host"`     // 主机地址
	Port     int32  `json:"port"`     // 端口号
	User     string `json:"user"`     // 用户名
	Password string `json:"password"` // 密码（建议在前端脱敏处理）
}

type SshInfoListResp struct {
	Items []*SshInfoDetailResp `json:"items"` // SSH记录列表
}
