// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetLogInfoReq struct {
	Logfile  string `form:"logfile"` //log name
	Path     string `form:"path"`    // log path
	Host     string `form:"host"`    // host address
	Password string `form:"password"`
	Match    string `form:"match"`
	Clean    string `form:"clean"`
	Posit    string `form:"posit"`
	Page     int    `form:"page"`
}

type GetLogInfoRes struct {
	Contents   []string `json:"contents"`
	Page       int      `json:"page"`
	TotalPages int      `json:"total_pages"`
	TotalLines int      `json:"total_lines"`
	MatchLines int      `json:"match_lines"`
	Lines      int      `json:"lines"`
}

type GetLogfileReq struct {
	ID            int    `json:"id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Path          string `json:"path"`
	CreateTime    int    `json:"create_time"`
	Comment       string `json:"comment"`
	MonitorChoice int    `json:"monitor_choice"`
}

type GetLogfileRes struct {
	Name          string   `json:"name"`
	Path          string   `json:"path"`
	Comment       string   `json:"comment"`
	Host          string   `json:"host"`
	Hosts         []string `json:"hosts"`
	MonitorChoice int      `json:"monitor_choice"`
}

type GetOperationLogReq struct {
	Page      int   `json:"page"`
	PageSize  int   `json:"page_size"`
	Flag      int   `json:"flag"`       //操作类型，0：上传，1：下载，2：删除，3.恢复 4：重命名，5：移动，6：复制，7：创建文件夹，8：修改文件, -1: 全部
	StartTime int64 `json:"start_time"` // 时间戳(秒)
	EndTime   int64 `json:"end_time"`   // 时间戳(秒)
}

type GetOperationLogRes struct {
	Total         int            `json:"total"`
	OperationLogs []OperationLog `json:"operation_logs"`
}

type GetPathsFileReq struct {
	LogFileName string `form:"path"` // log path
	Path        string `form:"path"` // log path
	Host        string `form:"host"` // host address
}

type GetPathsFileRes struct {
	PathsFile []string `json:"contents"`
}

type OperationLog struct {
	Content   string `json:"content"`
	FileSize  int    `json:"file_size"`
	CreatedAt string `json:"created_at"`
	Flag      int    `json:"flag"`
	FileName  string `json:"file_name"`
	FileId    string `json:"file_id"`
}
