// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_center.proto

package userservicerpc

import (
	"context"

	"github.com/Auroraol/cloud-storage/user_center/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVolumeReq            = pb.AddVolumeReq
	AddVolumeResp           = pb.AddVolumeResp
	CreateByShareReply      = pb.CreateByShareReply
	CreateByShareReq        = pb.CreateByShareReq
	DecreaseVolumeReq       = pb.DecreaseVolumeReq
	DecreaseVolumeResp      = pb.DecreaseVolumeResp
	FindRepositoryIdReply   = pb.FindRepositoryIdReply
	FindRepositoryIdReq     = pb.FindRepositoryIdReq
	FindVolumeReq           = pb.FindVolumeReq
	FindVolumeResp          = pb.FindVolumeResp
	RepositoryIdReq         = pb.RepositoryIdReq
	UserRepositoryNameReply = pb.UserRepositoryNameReply

	UserServiceRpc interface {
		DecreaseVolume(ctx context.Context, in *DecreaseVolumeReq, opts ...grpc.CallOption) (*DecreaseVolumeResp, error)
		FindVolumeById(ctx context.Context, in *FindVolumeReq, opts ...grpc.CallOption) (*FindVolumeResp, error)
		AddVolume(ctx context.Context, in *AddVolumeReq, opts ...grpc.CallOption) (*AddVolumeResp, error)
	}

	defaultUserServiceRpc struct {
		cli zrpc.Client
	}
)

func NewUserServiceRpc(cli zrpc.Client) UserServiceRpc {
	return &defaultUserServiceRpc{
		cli: cli,
	}
}

func (m *defaultUserServiceRpc) DecreaseVolume(ctx context.Context, in *DecreaseVolumeReq, opts ...grpc.CallOption) (*DecreaseVolumeResp, error) {
	client := pb.NewUserServiceRpcClient(m.cli.Conn())
	return client.DecreaseVolume(ctx, in, opts...)
}

func (m *defaultUserServiceRpc) FindVolumeById(ctx context.Context, in *FindVolumeReq, opts ...grpc.CallOption) (*FindVolumeResp, error) {
	client := pb.NewUserServiceRpcClient(m.cli.Conn())
	return client.FindVolumeById(ctx, in, opts...)
}

func (m *defaultUserServiceRpc) AddVolume(ctx context.Context, in *AddVolumeReq, opts ...grpc.CallOption) (*AddVolumeResp, error) {
	client := pb.NewUserServiceRpcClient(m.cli.Conn())
	return client.AddVolume(ctx, in, opts...)
}
