// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"cloud-storage/log_service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 日志文件
				Method:  http.MethodPost,
				Path:    "/logfiles",
				Handler: logfileHandler(serverCtx),
			},
			{
				// 路径文件
				Method:  http.MethodPost,
				Path:    "/path",
				Handler: pathHandler(serverCtx),
			},
			{
				// 日志阅读
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: readHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/log_service/v1"),
	)
}
