// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	RepositoryId int64  `json:"repository_id"`
	Name         string `json:"name"`
	Ext          string `json:"ext"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryId int64 `json:"user_repository_id"`
	ExpiredTime      int64 `json:"expiredTime"`
}

type ShareBasicCreateResponse struct {
	Id int64 `json:"id"`
}

type ShareBasicSaveRequest struct {
	RepositoryId int64 `json:"repository_id"` //分享的文件id
	ParentId     int64 `json:"parentId"`      //保存在该parentId目录下
}

type ShareBasicSaveResponse struct {
	Id int64 `json:"id"`
}
