// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DetailRequest struct {
	Id   string `form:"id"`
	Code string `form:"code"`
}

type DetailResponse struct {
	RepositoryId int64  `json:"repository_id"`
	Name         string `json:"name"`
	Ext          string `json:"ext"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryId int64  `json:"user_repository_id"` // 用户文件id
	RepositoryId     int64  `json:"repository_id"`      // 文件详情id
	ExpiredTime      int64  `json:"expired_time"`
	Code             string `json:"code"` // 提取码
}

type ShareBasicCreateResponse struct {
	Id string `json:"id"`
}

type ShareBasicDeleteRequest struct {
	Id string `form:"id"`
}

type ShareBasicDeleteResponse struct {
}

type ShareBasicDetailReply struct {
	Id           string `json:"id"`
	RepositoryId string `json:"repository_id"`
	Name         string `json:"name"`
	Owner        string `json:"owner"`
	Avatar       string `json:"avatar"`
	Ext          string `json:"ext"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
	ClickNum     int    `json:"click_num"`
	ExpiredTime  int    `json:"expired_time"`
	UpdateTime   string `json:"update_time"`
	Code         string `json:"code"`
}

type ShareBasicListRequest struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type ShareBasicListResponse struct {
	List  []*ShareBasicDetailReply `json:"list"`
	Total int64                    `json:"total"`
}

type ShareBasicSaveRequest struct {
	RepositoryId int64 `json:"repository_id"` //分享的文件id
	ParentId     int64 `json:"parent_id"`     //保存在该parentId目录下
}

type ShareBasicSaveResponse struct {
	Id string `json:"id"`
}
