// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CodeSendRequest struct {
	Email string `json:"email"`
}

type CodeSendResponse struct {
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RefreshAuthRequest struct {
}

type RefreshAuthResponse struct {
	AccesssToken string `json:"accesssToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Name     string `json:"name"`     // 用户名称
	Password string `json:"password"` // 用户密码
	Mobile   string `json:"mobile"`   // 手机号
	Code     string `json:"code"`     // 验证码
}

type RegisterResp struct {
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
