// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/Auroraol/cloud-storage/share_service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取资源详情
				Method:  http.MethodPost,
				Path:    "/share/basic/detail",
				Handler: ShareBasicDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/share_service/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建分享记录
				Method:  http.MethodPost,
				Path:    "/share/basic/create",
				Handler: ShareBasicCreateHandler(serverCtx),
			},
			{
				// 资源保存
				Method:  http.MethodPost,
				Path:    "/share/basic/save",
				Handler: ShareBasicSaveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/share_service/v1"),
	)
}
