// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_center.proto

package server

import (
	"context"

	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/logic/user"
	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/svc"
	"github.com/Auroraol/cloud-storage/user_center/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) DecreaseVolume(ctx context.Context, in *pb.DecreaseVolumeReq) (*pb.DecreaseVolumeResp, error) {
	l := userlogic.NewDecreaseVolumeLogic(ctx, s.svcCtx)
	return l.DecreaseVolume(in)
}

func (s *UserServer) FindVolumeById(ctx context.Context, in *pb.FindVolumeReq) (*pb.FindVolumeResp, error) {
	l := userlogic.NewFindVolumeByIdLogic(ctx, s.svcCtx)
	return l.FindVolumeById(in)
}

func (s *UserServer) AddVolume(ctx context.Context, in *pb.AddVolumeReq) (*pb.AddVolumeResp, error) {
	l := userlogic.NewAddVolumeLogic(ctx, s.svcCtx)
	return l.AddVolume(in)
}
