version: "3.8"

services:
  # 基础设施服务
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 741106
      MYSQL_DATABASE: cloud_storage
    ports:
      - "3306:3306"
    volumes:
      - /opt/project/mysql/data:/var/lib/mysql
      - /opt/project/mysql/conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    privileged: true
    networks:
      - cloud-network

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    command: --requirepass "741106"
    volumes:
      - /opt/project/redis/data:/data
      - /opt/project/redis/conf/redis.conf:/etc/redis/redis.conf
    privileged: true
    networks:
      - cloud-network

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - /opt/project/etcd_data:/bitnami/etcd
    networks:
      - cloud-network

  # 应用服务
  user-center:
    build:
      context: .
      dockerfile: docker/user_center/Dockerfile
    container_name: user-center
    restart: always
    ports:
      - "1004:1004"
    depends_on:
      - mysql
      - redis
      - etcd
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/project/logs:/app/logs
    networks:
      - cloud-network

  upload-service:
    build:
      context: .
      dockerfile: docker/upload_service/Dockerfile
    container_name: upload-service
    restart: always
    ports:
      - "1005:1005"
    depends_on:
      - mysql
      - redis
      - etcd
      - pulsar
    environment:
      - TZ=Asia/Shanghai
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET_NAME=${OSS_BUCKET_NAME}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
    volumes:
      - /opt/project/logs:/app/logs
    networks:
      - cloud-network

  share-service:
    build:
      context: .
      dockerfile: docker/share_service/Dockerfile
    container_name: share-service
    restart: always
    ports:
      - "1006:1006"
    depends_on:
      - mysql
      - redis
      - etcd
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/project/logs:/app/logs
    networks:
      - cloud-network

  log-service:
    build:
      context: .
      dockerfile: docker/log_service/Dockerfile
    container_name: log-service
    restart: always
    ports:
      - "1007:1007"
    depends_on:
      - mysql
      - etcd
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/project/logs:/app/logs
    networks:
      - cloud-network

  file-processor:
    build:
      context: .
      dockerfile: docker/file_processor/Dockerfile
    container_name: file-processor
    restart: always
    depends_on:
      - pulsar
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/project/logs:/app/logs
    networks:
      - cloud-network

  # Nginx反向代理
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/project/nginx/html:/usr/share/nginx/html
      - /opt/project/nginx/log:/var/log/nginx
      - /opt/project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/project/ssl:/etc/nginx/cert
    depends_on:
      - user-center
      - upload-service
      - share-service
    privileged: true
    networks:
      - cloud-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

# 网络配置
networks:
  # 内部网络，用于服务间通信
  cloud-network:
    driver: bridge 