global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-center'
    static_configs:
      - targets: ['user-center:8000']
    metrics_path: /metrics

  - job_name: 'upload-service'
    static_configs:
      - targets: ['upload-service:8001']
    metrics_path: /metrics

  - job_name: 'share-service'
    static_configs:
      - targets: ['share-service:8002']
    metrics_path: /metrics

  - job_name: 'log-service'
    static_configs:
      - targets: ['log-service:8003']
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']