// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_center.proto

package server

import (
	"context"

	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/logic/userservicerpc"
	"github.com/Auroraol/cloud-storage/user_center/rpc/internal/svc"
	"github.com/Auroraol/cloud-storage/user_center/rpc/pb"
)

type UserServiceRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceRpcServer
}

func NewUserServiceRpcServer(svcCtx *svc.ServiceContext) *UserServiceRpcServer {
	return &UserServiceRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceRpcServer) DecreaseVolume(ctx context.Context, in *pb.DecreaseVolumeReq) (*pb.DecreaseVolumeResp, error) {
	l := userservicerpclogic.NewDecreaseVolumeLogic(ctx, s.svcCtx)
	return l.DecreaseVolume(in)
}

func (s *UserServiceRpcServer) FindVolumeById(ctx context.Context, in *pb.FindVolumeReq) (*pb.FindVolumeResp, error) {
	l := userservicerpclogic.NewFindVolumeByIdLogic(ctx, s.svcCtx)
	return l.FindVolumeById(in)
}

func (s *UserServiceRpcServer) AddVolume(ctx context.Context, in *pb.AddVolumeReq) (*pb.AddVolumeResp, error) {
	l := userservicerpclogic.NewAddVolumeLogic(ctx, s.svcCtx)
	return l.AddVolume(in)
}
