// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetLogInfoReq struct {
	Logfile string `form:"logfile"`
	Path    string `form:"path"`
	Host    string `form:"host"`
	Match   string `form:"match"`
	Clean   string `form:"clean"`
	Posit   string `form:"posit"`
	Page    int    `form:"page"`
}

type GetLogInfoRes struct {
	Contents   []string `json:"contents"`
	Page       int      `json:"page"`
	TotalPages int      `json:"total_pages"`
	TotalLines int      `json:"total_lines"`
	MatchLines int      `json:"match_lines"`
	Lines      int      `json:"lines"`
}