// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	user "cloud-storage/user_center/cmd/api/internal/handler/user"
	"cloud-storage/user_center/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 验证码发送
				Method:  http.MethodPost,
				Path:    "/code/send",
				Handler: user.CodeSendHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user_center/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 刷新Authorization
				Method:  http.MethodPost,
				Path:    "/refresh/authorization",
				Handler: user.RefreshAuthorizationHandler(serverCtx),
			},
			{
				// 用户详情
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/user_center/v1"),
	)
}
