// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	oauth "github.com/Auroraol/cloud-storage/user_center/api/internal/handler/oauth"
	user "github.com/Auroraol/cloud-storage/user_center/api/internal/handler/user"
	"github.com/Auroraol/cloud-storage/user_center/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 账号密码登录
				Method:  http.MethodPost,
				Path:    "/oauth/login",
				Handler: oauth.LoginHandler(serverCtx),
			},
			{
				// 手机号登陆/注册
				Method:  http.MethodPost,
				Path:    "/oauth/login/mobile",
				Handler: oauth.LoginByMobileCodeHandler(serverCtx),
			},
			{
				// 账号密码注册
				Method:  http.MethodPost,
				Path:    "/oauth/register",
				Handler: oauth.RegisterHandler(serverCtx),
			},
			{
				// 验证码发送
				Method:  http.MethodPost,
				Path:    "/oauth/send",
				Handler: oauth.CodeSendHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user_center/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 刷新Authorization
				Method:  http.MethodPost,
				Path:    "/refresh/authorization",
				Handler: user.RefreshAuthorizationHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/user_center/v1"),
	)
}
