// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	audit "github.com/Auroraol/cloud-storage/log_service/api/internal/handler/audit"
	monitor "github.com/Auroraol/cloud-storage/log_service/api/internal/handler/monitor"
	ssh "github.com/Auroraol/cloud-storage/log_service/api/internal/handler/ssh"
	"github.com/Auroraol/cloud-storage/log_service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 分页获得操作日志
				Method:  http.MethodPost,
				Path:    "/operation",
				Handler: audit.OperationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/log_service/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 历史分析
				Method:  http.MethodPost,
				Path:    "/monitor/history",
				Handler: monitor.HistoryAnalysisLogicHandler(serverCtx),
			},
			{
				// 实时监控
				Method:  http.MethodPost,
				Path:    "/monitor/realtime",
				Handler: monitor.RealTimeMonitorHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/log_service/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// SSH连接
				Method:  http.MethodPost,
				Path:    "/ssh/connect",
				Handler: ssh.ConnectHandler(serverCtx),
			},
			{
				// 删除SSH连接信息
				Method:  http.MethodPost,
				Path:    "/ssh/delete",
				Handler: ssh.DeleteSSHConnectHandler(serverCtx),
			},
			{
				// 获取SSH连接信息
				Method:  http.MethodPost,
				Path:    "/ssh/get",
				Handler: ssh.GetSSHConnectHandler(serverCtx),
			},
			{
				// 读取日志文件
				Method:  http.MethodPost,
				Path:    "/ssh/logfiles",
				Handler: ssh.ReadLogFileHandler(serverCtx),
			},
			{
				// 获取日志文件列表
				Method:  http.MethodPost,
				Path:    "/ssh/readlog",
				Handler: ssh.GetLogFilesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/log_service/v1"),
	)
}
