// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.0
// source: log_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileSize      int32                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"` //文件大小
	Flag          int32                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`         // 操作类型，0：上传，1：下载，2：删除，3.恢复 4：重命名，5：移动，6：复制，7：创建文件夹，8：修改文件
	FileName      string                 `protobuf:"bytes,5,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileId        int64                  `protobuf:"varint,6,opt,name=fileId,proto3" json:"fileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogReq) Reset() {
	*x = OperationLogReq{}
	mi := &file_log_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogReq) ProtoMessage() {}

func (x *OperationLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogReq.ProtoReflect.Descriptor instead.
func (*OperationLogReq) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *OperationLogReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationLogReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OperationLogReq) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *OperationLogReq) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *OperationLogReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *OperationLogReq) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type OperationLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogResp) Reset() {
	*x = OperationLogResp{}
	mi := &file_log_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogResp) ProtoMessage() {}

func (x *OperationLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogResp.ProtoReflect.Descriptor instead.
func (*OperationLogResp) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperationLogResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 新增消息类型
type SshInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 关联用户ID
	Host          string                 `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`      // 主机地址
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`     // 端口号
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshInfoReq) Reset() {
	*x = SshInfoReq{}
	mi := &file_log_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshInfoReq) ProtoMessage() {}

func (x *SshInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshInfoReq.ProtoReflect.Descriptor instead.
func (*SshInfoReq) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{2}
}

func (x *SshInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SshInfoReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SshInfoReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SshInfoReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SshInfoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteSshInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshId         int64                  `protobuf:"varint,1,opt,name=sshId,proto3" json:"sshId,omitempty"` // SSH记录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSshInfoReq) Reset() {
	*x = DeleteSshInfoReq{}
	mi := &file_log_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSshInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSshInfoReq) ProtoMessage() {}

func (x *DeleteSshInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSshInfoReq.ProtoReflect.Descriptor instead.
func (*DeleteSshInfoReq) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSshInfoReq) GetSshId() int64 {
	if x != nil {
		return x.SshId
	}
	return 0
}

type SshInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 记录ID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 操作状态
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 附加信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshInfoResp) Reset() {
	*x = SshInfoResp{}
	mi := &file_log_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshInfoResp) ProtoMessage() {}

func (x *SshInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshInfoResp.ProtoReflect.Descriptor instead.
func (*SshInfoResp) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{4}
}

func (x *SshInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SshInfoResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SshInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询请求参数
type GetSshInfosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 关联用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSshInfosReq) Reset() {
	*x = GetSshInfosReq{}
	mi := &file_log_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSshInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSshInfosReq) ProtoMessage() {}

func (x *GetSshInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSshInfosReq.ProtoReflect.Descriptor instead.
func (*GetSshInfosReq) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetSshInfosReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 详细信息响应
type SshInfoDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 关联用户ID
	SshId         int64                  `protobuf:"varint,2,opt,name=sshId,proto3" json:"sshId,omitempty"`   // SSH记录ID
	Host          string                 `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`      // 主机地址
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`     // 端口号
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshInfoDetailResp) Reset() {
	*x = SshInfoDetailResp{}
	mi := &file_log_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshInfoDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshInfoDetailResp) ProtoMessage() {}

func (x *SshInfoDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshInfoDetailResp.ProtoReflect.Descriptor instead.
func (*SshInfoDetailResp) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{6}
}

func (x *SshInfoDetailResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SshInfoDetailResp) GetSshId() int64 {
	if x != nil {
		return x.SshId
	}
	return 0
}

func (x *SshInfoDetailResp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SshInfoDetailResp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SshInfoDetailResp) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SshInfoDetailResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 列表响应
type SshInfoListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SshInfoDetailResp   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshInfoListResp) Reset() {
	*x = SshInfoListResp{}
	mi := &file_log_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshInfoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshInfoListResp) ProtoMessage() {}

func (x *SshInfoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshInfoListResp.ProtoReflect.Descriptor instead.
func (*SshInfoListResp) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{7}
}

func (x *SshInfoListResp) GetItems() []*SshInfoDetailResp {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_log_service_proto protoreflect.FileDescriptor

var file_log_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa7, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x22, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7c, 0x0a, 0x0a, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x73, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x73, 0x68, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x73, 0x68, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x0b, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x53,
	0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x73, 0x68, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x73, 0x68, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3e, 0x0a, 0x0f, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x73,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x52, 0x0a, 0x0f, 0x41, 0x75, 0x64, 0x69, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x70, 0x63, 0x12, 0x3f, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x32, 0xae, 0x01, 0x0a, 0x0d, 0x53,
	0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x70, 0x63, 0x12, 0x2e, 0x0a, 0x0b,
	0x53, 0x61, 0x76, 0x65, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x73, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x73, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x73, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_service_proto_rawDescOnce sync.Once
	file_log_service_proto_rawDescData = file_log_service_proto_rawDesc
)

func file_log_service_proto_rawDescGZIP() []byte {
	file_log_service_proto_rawDescOnce.Do(func() {
		file_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_service_proto_rawDescData)
	})
	return file_log_service_proto_rawDescData
}

var file_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_log_service_proto_goTypes = []any{
	(*OperationLogReq)(nil),   // 0: pb.OperationLogReq
	(*OperationLogResp)(nil),  // 1: pb.OperationLogResp
	(*SshInfoReq)(nil),        // 2: pb.SshInfoReq
	(*DeleteSshInfoReq)(nil),  // 3: pb.DeleteSshInfoReq
	(*SshInfoResp)(nil),       // 4: pb.SshInfoResp
	(*GetSshInfosReq)(nil),    // 5: pb.GetSshInfosReq
	(*SshInfoDetailResp)(nil), // 6: pb.SshInfoDetailResp
	(*SshInfoListResp)(nil),   // 7: pb.SshInfoListResp
}
var file_log_service_proto_depIdxs = []int32{
	6, // 0: pb.SshInfoListResp.items:type_name -> pb.SshInfoDetailResp
	0, // 1: pb.AuditServiceRpc.CreateOperationLog:input_type -> pb.OperationLogReq
	2, // 2: pb.SshServiceRpc.SaveSshInfo:input_type -> pb.SshInfoReq
	3, // 3: pb.SshServiceRpc.DeleteSshInfo:input_type -> pb.DeleteSshInfoReq
	5, // 4: pb.SshServiceRpc.GetSshInfo:input_type -> pb.GetSshInfosReq
	1, // 5: pb.AuditServiceRpc.CreateOperationLog:output_type -> pb.OperationLogResp
	4, // 6: pb.SshServiceRpc.SaveSshInfo:output_type -> pb.SshInfoResp
	4, // 7: pb.SshServiceRpc.DeleteSshInfo:output_type -> pb.SshInfoResp
	7, // 8: pb.SshServiceRpc.GetSshInfo:output_type -> pb.SshInfoListResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_log_service_proto_init() }
func file_log_service_proto_init() {
	if File_log_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_log_service_proto_goTypes,
		DependencyIndexes: file_log_service_proto_depIdxs,
		MessageInfos:      file_log_service_proto_msgTypes,
	}.Build()
	File_log_service_proto = out.File
	file_log_service_proto_rawDesc = nil
	file_log_service_proto_goTypes = nil
	file_log_service_proto_depIdxs = nil
}
