// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.0
// source: log_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileSize      int32                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"` //文件大小
	Flag          int32                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`         // 操作类型，0：上传，1：下载，2：删除，3.恢复 4：重命名，5：移动，6：复制，7：创建文件夹，8：修改文件
	FileName      string                 `protobuf:"bytes,5,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileId        int64                  `protobuf:"varint,6,opt,name=fileId,proto3" json:"fileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogReq) Reset() {
	*x = OperationLogReq{}
	mi := &file_log_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogReq) ProtoMessage() {}

func (x *OperationLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogReq.ProtoReflect.Descriptor instead.
func (*OperationLogReq) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *OperationLogReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationLogReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OperationLogReq) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *OperationLogReq) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *OperationLogReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *OperationLogReq) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type OperationLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogResp) Reset() {
	*x = OperationLogResp{}
	mi := &file_log_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogResp) ProtoMessage() {}

func (x *OperationLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_log_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogResp.ProtoReflect.Descriptor instead.
func (*OperationLogResp) Descriptor() ([]byte, []int) {
	return file_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperationLogResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_log_service_proto protoreflect.FileDescriptor

var file_log_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa7, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x22, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x52, 0x0a, 0x0f, 0x41, 0x75, 0x64, 0x69, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x70, 0x63, 0x12, 0x3f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_service_proto_rawDescOnce sync.Once
	file_log_service_proto_rawDescData = file_log_service_proto_rawDesc
)

func file_log_service_proto_rawDescGZIP() []byte {
	file_log_service_proto_rawDescOnce.Do(func() {
		file_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_service_proto_rawDescData)
	})
	return file_log_service_proto_rawDescData
}

var file_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_service_proto_goTypes = []any{
	(*OperationLogReq)(nil),  // 0: pb.OperationLogReq
	(*OperationLogResp)(nil), // 1: pb.OperationLogResp
}
var file_log_service_proto_depIdxs = []int32{
	0, // 0: pb.AuditServiceRpc.CreateOperationLog:input_type -> pb.OperationLogReq
	1, // 1: pb.AuditServiceRpc.CreateOperationLog:output_type -> pb.OperationLogResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_log_service_proto_init() }
func file_log_service_proto_init() {
	if File_log_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_service_proto_goTypes,
		DependencyIndexes: file_log_service_proto_depIdxs,
		MessageInfos:      file_log_service_proto_msgTypes,
	}.Build()
	File_log_service_proto = out.File
	file_log_service_proto_rawDesc = nil
	file_log_service_proto_goTypes = nil
	file_log_service_proto_depIdxs = nil
}
