// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type FileUploadByChunkRequest struct {
}

type FileUploadByChunkResponse struct {
	Id string `json:"id"`
}

type FileUploadRequest struct {
}

type FileUploadResponse struct {
	Id string `json:"id"`
}
