// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: upload_service.proto

package uploadservice

import (
	"context"

	"github.com/Auroraol/cloud-storage/upload_service/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteByIdReq  = pb.DeleteByIdReq
	DeleteByIdResp = pb.DeleteByIdResp
	RepositoryReq  = pb.RepositoryReq
	RepositoryResp = pb.RepositoryResp

	UploadService interface {
		GetRepositoryPoolByRepositoryId(ctx context.Context, in *RepositoryReq, opts ...grpc.CallOption) (*RepositoryResp, error)
		DeleteById(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*DeleteByIdResp, error)
	}

	defaultUploadService struct {
		cli zrpc.Client
	}
)

func NewUploadService(cli zrpc.Client) UploadService {
	return &defaultUploadService{
		cli: cli,
	}
}

func (m *defaultUploadService) GetRepositoryPoolByRepositoryId(ctx context.Context, in *RepositoryReq, opts ...grpc.CallOption) (*RepositoryResp, error) {
	client := pb.NewUploadServiceClient(m.cli.Conn())
	return client.GetRepositoryPoolByRepositoryId(ctx, in, opts...)
}

func (m *defaultUploadService) DeleteById(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*DeleteByIdResp, error) {
	client := pb.NewUploadServiceClient(m.cli.Conn())
	return client.DeleteById(ctx, in, opts...)
}
